core:
  seed:
    alias: S
    type: int
    help: "Random seed (default: None)"
  episodes:
    alias: E
    type: int
    default: 2000
    help: "Number of episodes (default: 2000)"
  eval-timesteps:
    alias: V
    type: int
    default: 2000
    help: "Approximate number of timesteps during eval period (default: 2000)"
  eval-every:
    alias: EE
    type: int
    default: 100
    help: "Number of episodes between eval periods (default: 100)"
  eval-visualize-episodes:
    alias: EV
    type: int
    default: 4
    help: "Number of episodes from the evaluation to visualize in tensorboard (default: 4)"
  discount:
    alias: D
    type: float
    default: .99
    help: "Agent-death probability complement. (default: 0.99)"
  cheat:
    alias: C
    action: store_true
    help: "Whether to learn directly from hidden performance score (default: False)"
  log-dir:
    alias: L
    type: str
    help: "Subdirectory to write logs to for this run (defaults to combo of env, agent, cheating, seed)"
  disable-cuda:
    alias: dc
    action: store_true
    help: "Disable CUDA computations (default: False)"
  tune:
    alias: t
    action: append
    type: str
    help: "Use Ray Tune to tune this parameter"
